CREATE TABLE `lyrics`.`request` ( `id` INT NOT NULL AUTO_INCREMENT , `time` DATETIME NULL DEFAULT NULL , `uri` VARCHAR(50) NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `lyrics`.`songTV` ( `id` INT NOT NULL AUTO_INCREMENT , `title` VARCHAR(100) NULL DEFAULT NULL , `author` VARCHAR(50) NULL DEFAULT NULL , `content` LONGTEXT NULL DEFAULT NULL , `creator` VARCHAR(50) NULL DEFAULT NULL , `dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

